Vidu:
   ListenHost: 0.0.0.0
   ListenPort: :8080
   MaxSub: 2
   Vidu1:
      URL: https://openvidu1.com
      User: user1
      Password: pass1
   Vidu2:
      URL: https://openvidu2.com
      User: user2
      Password: pass2
